# Generated by Django 4.1.1 on 2022-10-04 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('severity', models.CharField(choices=[('S', 'severe'), ('M', 'moderate'), ('L', 'mild')], default='high', max_length=20)),
                ('description', models.TextField()),
                ('attachment', models.FileField(upload_to='uploads/')),
                ('state', models.CharField(choices=[('O', 'open'), ('C', 'closed'), ('R', 'reopened')], default='open', max_length=20)),
                ('date_added', models.DateField()),
                ('reported_by', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
