# Generated by Django 4.1.1 on 2022-10-04 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_alter_team_teamleadermail'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assigned_to',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.team'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
