# Generated by Django 4.0.5 on 2022-10-05 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_name'),
        ('report', '0002_report_assigned_to_alter_report_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.project'),
        ),
    ]
