# Generated by Django 4.0.5 on 2022-10-05 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0004_remove_report_assigned_to_alter_report_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigne', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='submitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.CharField(choices=[('S', 'severe'), ('n', 'noraml'), ('L', 'mild')], default='high', max_length=20),
        ),
    ]
