# Generated by Django 4.1.1 on 2022-10-06 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0005_report_assigned_to_alter_report_reported_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.CharField(choices=[('Severe', 'severe'), ('Normal', 'normal'), ('Mild', 'mild')], default='high', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.CharField(choices=[('Open', 'open'), ('Closed', 'closed'), ('Reopened', 'reopened')], default='open', max_length=20),
        ),
    ]
