# Generated by Django 4.1.1 on 2022-10-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_report_attachment_alter_report_belongs_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.CharField(choices=[('Severe', 'severe'), ('Normal', 'normal'), ('Mild', 'mild')], default='severe', max_length=20),
        ),
    ]
