# Generated by Django 4.0.5 on 2022-10-10 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0007_alter_report_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assign', to=settings.AUTH_USER_MODEL),
        ),
    ]
