# Generated by Django 4.0.5 on 2022-10-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.report'),
        ),
    ]
