# Generated by Django 4.0.5 on 2022-10-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_comment_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(blank=True, null=True, to='report.comment'),
        ),
    ]
