# Generated by Django 4.0.5 on 2022-10-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_remove_comment_parent_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(blank=True, to='report.comment'),
        ),
    ]
