# Generated by Django 4.0.5 on 2022-10-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_alter_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies_count',
            field=models.IntegerField(default=0),
        ),
    ]
