# Generated by Django 4.0.5 on 2022-10-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_comment_replies_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='thread_top',
            field=models.BooleanField(default=False),
        ),
    ]
