# Generated by Django 4.0.5 on 2022-10-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_comment_thread_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replies_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='thread_top',
        ),
    ]
