# Generated by Django 4.0.5 on 2022-10-12 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0019_alter_report_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assign', to=settings.AUTH_USER_MODEL),
        ),
    ]
