# Generated by Django 4.0.5 on 2022-10-12 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_alter_project_name'),
        ('report', '0020_alter_report_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='assign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
