# Generated by Django 4.0.5 on 2022-10-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_alter_comment_commented_by_alter_comment_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.CharField(choices=[('Open', 'open'), ('Closed', 'closed')], default='open', max_length=20),
        ),
    ]
