# Generated by Django 4.0.5 on 2022-09-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('assigned_to', models.CharField(max_length=30)),
                ('closed', models.BooleanField()),
            ],
        ),
    ]
