# Generated by Django 4.1 on 2022-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('teamleader', models.CharField(max_length=20)),
                ('bugsreported', models.IntegerField()),
                ('bugsclosed', models.IntegerField()),
            ],
        ),
    ]
