# Generated by Django 4.0.5 on 2022-09-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='teamleader',
            new_name='teamleadermail',
        ),
    ]
