# Generated by Django 4.0.5 on 2022-09-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_teamleader_user_teamleadermail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teamleadermail',
            field=models.EmailField(max_length=254),
        ),
    ]
