# Generated by Django 4.0.5 on 2022-09-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_teamleadermail_user_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
